FROM ajaysehwal81/wazo-confd

RUN true \
    && apt-get update && apt-get install -y \
      postgresql-client \
      postgresql-server-dev-all \
      libpq-dev \
      netcat \
      wget \
      gcc \
      python3-dev \
    && pip install \
      alembic==1.0.0 \
      https://github.com/wazo-platform/wazo-uuid/archive/master.zip \
      https://github.com/wazo-platform/xivo-manage-db/archive/master.zip \
      https://github.com/wazo-platform/wazo-asterisk-doc-extractor/archive/master.zip \
    && adduser --quiet --system --group --shell /bin/bash postgres \
    && mkdir -p /var/lib/wazo-confd \
    && mkdir -p /usr/lib/xivo-manage-db \
    && rm -f /usr/lib/xivo-manage-db/pg-populate-db && ln -s /opt/venv/bin/pg-populate-db /usr/lib/xivo-manage-db/pg-populate-db \
    && wget -q -O- https://github.com/wazo-platform/xivo-manage-db/archive/master.tar.gz | tar -xz -C /usr/share --transform s/-master// \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
