FROM ajaysehwal81/wazo-auth-cli

RUN true \
    && apt-get update && apt-get install -y \
      libpq-dev \
      gcc \
      python3-dev \
      dnsutils \
      iproute2 \
      curl \
    && pip install \
      psycopg2-binary==2.8.6 \
      https://github.com/wazo-platform/wazo-auth-keys/archive/master.zip \
    && mkdir -p /etc/wazo-auth-keys/conf.d \
    && mkdir -p /var/lib/wazo-auth-keys \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
