FROM ajaysehwal81/asterisk

RUN apt-get update
RUN apt-get install -y asterisk-core-sounds-en-gsm odbc-postgresql
# Wazo sounds packages are not available in standard repos, skipping for now
# RUN apt-get install -y wazo-sounds-en-us wazo-sounds-fr-ca wazo-sounds-fr-fr
RUN apt-get install -y netcat

RUN apt-get update && apt-get install -y python3 python3-venv
RUN python3 -m venv /opt/venv3
# Activate virtual env
ENV PATH="/opt/venv3/bin:$PATH"

RUN pip3 install wheel
RUN pip3 install https://github.com/wazo-platform/wazo-confgend-client/archive/master.zip
RUN rm -f /usr/bin/wazo-confgen && ln -s /opt/venv3/bin/wazo-confgen /usr/bin/wazo-confgen

# Configure ARI for confd
RUN echo "[general]" > /etc/asterisk/ari.conf
RUN echo "enabled = yes" >> /etc/asterisk/ari.conf
RUN echo "pretty = yes" >> /etc/asterisk/ari.conf
RUN echo "" >> /etc/asterisk/ari.conf
RUN echo "[xivo]" >> /etc/asterisk/ari.conf
RUN echo "type = user" >> /etc/asterisk/ari.conf
RUN echo "password = Nasheow8Eag" >> /etc/asterisk/ari.conf
RUN echo "read_only = no" >> /etc/asterisk/ari.conf
RUN echo "password_format = plain" >> /etc/asterisk/ari.conf

# Configure DUNDI for pbx_dundi module
RUN echo "[general]" > /etc/asterisk/dundi.conf
RUN echo "department = IT" >> /etc/asterisk/dundi.conf
RUN echo "organization = Wazo" >> /etc/asterisk/dundi.conf
RUN echo "locality = Local" >> /etc/asterisk/dundi.conf
RUN echo "stateprov = State" >> /etc/asterisk/dundi.conf
RUN echo "country = US" >> /etc/asterisk/dundi.conf
RUN echo "bindaddr = 0.0.0.0" >> /etc/asterisk/dundi.conf
RUN echo "port = 4520" >> /etc/asterisk/dundi.conf
RUN echo "host = 0.0.0.0" >> /etc/asterisk/dundi.conf
RUN echo "family = ipv4" >> /etc/asterisk/dundi.conf
RUN echo "model = symmetric" >> /etc/asterisk/dundi.conf
RUN echo "autokill = yes" >> /etc/asterisk/dundi.conf

# Configure HEP to enable res_hep modules
RUN echo "[general]" > /etc/asterisk/hep.conf
RUN echo "enabled = yes" >> /etc/asterisk/hep.conf
RUN echo "capture_address = 127.0.0.1:9061" >> /etc/asterisk/hep.conf
RUN echo "capture_password = " >> /etc/asterisk/hep.conf
RUN echo "capture_id = 1234" >> /etc/asterisk/hep.conf
RUN echo "uuid_type = call-id" >> /etc/asterisk/hep.conf

# Configure HTTP for AJAM support
RUN echo "[general]" > /etc/asterisk/http.conf
RUN echo "enabled = yes" >> /etc/asterisk/http.conf
RUN echo "bindaddr = 0.0.0.0" >> /etc/asterisk/http.conf
RUN echo "bindport = 5039" >> /etc/asterisk/http.conf
RUN echo "prefix = " >> /etc/asterisk/http.conf
RUN echo "enablestatic = yes" >> /etc/asterisk/http.conf

# Add AJAM server
COPY bin/ajam-server.py /usr/local/bin/ajam-server.py
RUN chmod +x /usr/local/bin/ajam-server.py
