[moto_auth]
type=auth
username=moto
password=moto2
auth_type=userpass

[moto_aor]
type=aor
max_contacts=1
qualify_frequency=60

[moto]
type=endpoint
transport=transport-udp-local
context=from-internal
disallow=all
allow=ulaw,alaw
auth=moto_auth
aors=moto_aor
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
