[general]
enabled = yes
webenabled = no
bindaddr = 0.0.0.0
port = 5038
allowmultiplelogin = yes
displayconnects = yes

[wazo_amid]
username=wazo_amid
secret=eeCho8ied3u
permit=0.0.0.0/0.0.0.0
read=all
write=all
writetimeout = 2000
