[moto]
type=endpoint
transport=transport-udp-local
context=ctx-mycompany-internal-2a6e174d-f496-4bb0-91ab-d5621735e1c5
disallow=all
allow=ulaw
auth=moto_auth
aors=moto_aor

[moto_auth]
type=auth
username=moto
password=moto2
auth_type=userpass

[moto_aor]
type=aor
max_contacts=1
remove_existing=yes
