[transport-udp-local]
type=transport
protocol=udp
bind=0.0.0.0:5060
allow_reload=yes

[uno]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=uno-auth
aors=uno
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
transport=transport-udp-local
dtmf_mode=rfc4733
allow_transfer=yes
trust_id_inbound=yes
trust_id_outbound=yes
send_rpid=yes
timers_sess_expires=3600
from_user=uno
from_domain=134.185.85.234

[uno-auth]
type=auth
auth_type=userpass
password=password123
username=uno
realm=asterisk
md5_cred=
nonce_lifetime=300

[uno]
type=aor
max_contacts=5
remove_existing=yes
qualify_frequency=60
